# frozen_string_literal: true

module Vdd
  VERSION = "0.1.0"
end

require_relative "vdd/errors"
require_relative "vdd/command"
require_relative "vdd/manifest"
require_relative "vdd/context"
require_relative "vdd/logging"
require_relative "vdd/reporter"
require_relative "vdd/runner"
require_relative "vdd/installer"
require_relative "vdd/product_test"
require_relative "vdd/adapters/legacy_scripts"
require_relative "vdd/ai/codex"
require_relative "vdd/ai/claude"
require_relative "vdd/ai/antigravity"
require_relative "vdd/ai/gemini"
require_relative "vdd/ai/provider"
require_relative "vdd/ai/provider_config"
require_relative "vdd/commands/git_state"
require_relative "vdd/commands/status"
require_relative "vdd/commands/list"
require_relative "vdd/commands/diff"
require_relative "vdd/commands/logs"
require_relative "vdd/commands/test"
require_relative "vdd/deploy/github"
require_relative "vdd/deploy/repository"
require_relative "vdd/commands/deploy"
require_relative "vdd/checks/command"
require_relative "vdd/checks/javascript"
require_relative "vdd/checks/workspace"
require_relative "vdd/commands/doctor"
require_relative "vdd/commands/doctor_fix"
require_relative "vdd/cli"
